# Create a shopping item for a specific customer
POST http://localhost:8080/shopping-list/Mohit
Content-Type: application/json

{
  "name": "Milk"
}

# List all shopping items for a specific customer
GET http://localhost:8080/shopping-list/{customer}

# Delete a shopping item for a specific customer by ID
DELETE http://localhost:8080/shopping-list/{customer}/{id}
