# Create a shopping item for a specific customer
POST http://localhost:8080/shopping-list/"CustomerName"
Content-Type: application/json

{
  "name": "milk",
  "quantity": 10
}


# List all shopping items for a specific customer
GET http://localhost:8080/shopping-list/"CustomerName"

# Delete a shopping item for a specific customer by ID
DELETE http://localhost:8080/shopping-list/"CustomerName"/"ItemID"